# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

inhibit_all_warnings!

target 'DeepOC' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DeepOC

pod 'YYModel'
pod 'YYCache'
pod 'YYWebImage'
pod 'YYText'
pod 'YTKNetwork'
pod 'YYCategories'

end
